### ISSUE TITLE
Please consider deleting this, since it's empty and you haven't touched it for 2 years

### ISSUE THREAD

**Issue by ric2b** [MagicAndi/OneNoteToMarkdown#1]
I'm sorry but you gave me so much hope when I found this repo, only to have my dreams crushed when I noticed it was a hollow box of lies and disapointment :'(

(I'm not trying to offend you, I'm only half serious here :p My heart _did_ break though)

**Comment by MagicAndi** [comment]
Hi Ricardo,

Thanks for your interest. Apologies that the project disappointed you. I do have a working POC for converting OneNote journals into a directory of MD files, but have yet to commit the code, due to a number of issues:

1) The initial client is built as a desktop application and makes use of an old MS OneNote .NET wrapper (https://onom.codeplex.com/). I had to hack this considerably and wouldn't be happy releasing this code on quality grounds. There may also be licencing issues.  I probably should have used the Office 365/OneNote API instead, but I was attempting to avoid any web dependencies for what I seen as a desktop app.

2) Issues around converting tables in OneNote into tables in MD. Seems like a minor problem, but it actually quite convoluted. I make a lot of use of tables in my OneNote notebooks, so this is a big issue for me personally.

Until I get around to fixing these issues, the repo will remain empty. You may be disappointed by an empty repo - I can assure you that others are even more disappointed by buggy code, or desktop applications that don't work on their version of Windows. Unfortunately, I'm working on other projects now and have new family commitments, so it is unlikely I get time for this work soon. Apologies. I have updated the project readme file accordingly. Thanks.

Regards,
Andy
